version: "3.9"
services:

  # Nginx reverse proxy
  nginx:
    depends_on:
      # - web
      - backend
      - imgproxy
    restart: always # Essential since it routes traffic to our entire app
    build: ./nginx
    ports: 
      - 80:80

  # Elixir app
  backend:
    # image: ghcr.io/onomated/countdownplus/countdownplus-elixir:latest
    build: ../countdownplus-elixir/artifacts/releases/prod/countdownplus_app
    expose:
      - "4000"
    environment:
      - PORT=4000
    env_file:
      - app_local.env

  # Imgproxy
  imgproxy:
    image: darthsim/imgproxy
    expose:
      - "8080"
    environment:
      - IMGPROXY_DEVELOPMENT_ERRORS_MODE=true
    env_file:
      - app_local.env

  # NextJS app
  # web:
  #   # image: ghcr.io/onomated/countdownplus/countdownplus-web:latest
  #   build: ../cplus-web/artifacts/release
  #   depends_on:
  #     - backend
  #     - imgproxy
  #   expose:
  #     - "3000"
  #   environment:
  #     - PORT=3000
  #   env_file:
  #     - app_local.env
