defmodule Countdownplus.Repo.Migrations.CreateEnums do
  use Ecto.Migration

  alias Countdownplus.Types.Enums.{
    AccountType,
    ActivityType,
    ActivityEntity,
    AppEdition,
    ArticleType,
    AttachmentType,
    AttachmentProvider,
    AuthMethod,
    AuthProvider,
    CountUnit,
    DevicePlatform,
    EventAccessMode,
    EventProvider,
    EventType,
    Pronoun,
    GroupAccessMode,
    GroupMembershipStatus,
    GroupMembershipType,
    # InvitationResponse,
    # NotificationChannel,
    ProfileAttachmentType,
    PurchaseModel,
    RelationshipType,
    # ReminderUnit,
  }

  def change do
    for enum_mod <- [
          AccountType,
          ActivityEntity,
          ActivityType,
          AppEdition,
          ArticleType,
          AttachmentType,
          AttachmentProvider,
          AuthMethod,
          AuthProvider,
          CountUnit,
          DevicePlatform,
          EventAccessMode,
          EventProvider,
          EventType,
          Pronoun,
          GroupAccessMode,
          GroupMembershipStatus,
          GroupMembershipType,
          # InvitationResponse,
          # NotificationChannel,
          PurchaseModel,
          ProfileAttachmentType,
          RelationshipType,
          # ReminderUnit,
        ],
        do: enum_mod.create_type()
  end
end
