name: Deploy to Prod
env:
  APP_NAME: countdownplus
  APP_ENV: prod
  AWS_REGION: us-east-1
  BEANSTALK_APP_NAME: Countdownplus
  BEANSTALK_ENV_NAME: countdownplus

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy env file from s3
        run: |
          aws s3 cp s3://appsbeyond-configs/${{ env.APP_NAME }}/production/cplus_prod.env .env

      - name: Generate deployment package
        run: zip -r deploy.zip . -x ".git**" "docs**" "docker-compose-*.yml"

      - name: Beanstalk Deploy for app
        # v21
        uses: einaregilsson/beanstalk-deploy@18e5b85bd914cabf00fccabe72f60b8757dcd3cb
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          application_name: ${{ env.BEANSTALK_APP_NAME }}
          environment_name: ${{ env.BEANSTALK_ENV_NAME }}
          version_label: ${{ github.run_number }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
#      - name: Notify Status
#        uses: sonots/slack-notice-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required
#        with:
#          status: ${{ job.status }}
#          text: 'Countdown+ Prod Deployment'
#          icon_emoji: ':rocket:'
#        if: always()
